data.setBooleanParameter(true);
data.setDateParameter(new Date());
data.setDateTimeParameter(new Date());
data.setNumberDecimalParameter(123.45);
data.setNumberIntegerParameter(123);
data.setPerformerParameter("Participant");
data.setTextParameter("Some text");
data.setTimeParameter(new Date());
data.setUriParameter("https://www.tibco.com/");
logger.info("Set form data");